name: KeyBoi
main: com.ruinscraft.keyboi.KeyBoi
version: 1.0
author: Ruinscraft LLC
api-version: 1.16
commands:
  key:
    description: Shows all commands for KeyBoi
    usage: /key
    permission: keyboi.general